OPENSSL_VERSION   := 3.0.5
OPENSSL_MIRROR    := https://www.openssl.org/source
OPUS_VERSION      := 1.3.1
OPUS_MIRROR       := https://archive.mozilla.org/pub/opus
PORTAUDIO_VERSION := 19.7.0
PORTAUDIO_MIRROR  := https://github.com/PortAudio/portaudio/archive/refs/tags
LIBRE_VERSION     := main
LIBREM_VERSION    := main
BARESIP_VERSION   := main
CACHE_VERSION     := 0.0.4 # github cache invalidation workaround
