#
# Makefile
#
# Copyright (C) 2021 Studio.Link Sebastian Reimers
#

LIBRE_MK     := ../third_party/re/mk/re.mk
LIBREM_PATH  := ../third_party/rem
BARESIP_PATH := ../third_party/baresip

include $(LIBRE_MK)
