FIND_PATH(FLAC_INCLUDE_DIR FLAC/metadata.h HINTS include)

FIND_LIBRARY(FLAC_LIBRARIES NAMES FLAC HINTS lib)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FLAC DEFAULT_MSG FLAC_LIBRARIES FLAC_INCLUDE_DIR)

# show the FLAC_INCLUDE_DIR and FLAC_LIBRARIES variables only in the advanced view
MARK_AS_ADVANCED(FLAC_INCLUDE_DIR FLAC_LIBRARIES)
