# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  webui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'webui/package-lock.json'
    - run: cd webui && npm install
    - run: cd webui && npm run build

  ccheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ccheck
      run: make ccheck

  build:
    runs-on: ${{ matrix.os }}
    needs: webui
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.10"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
            third_party
            !third_party/re
            !third_party/rem
            !third_party/baresip
            !third_party/include/re
            !third_party/include/rem
        key: ${{ runner.os }}-${{ hashFiles('versions.mk') }}
    - name: make StudioLink
      run: make
